# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://hrhr49.github.io/memo/"  # Include trailing slash
title = "hrhr49 blog"
enableInlineShortcodes = true
defaultContentLanguage = "ja"
languageCode = "ja-jp"
disablePathToLower = true
hasCJKLanguage = true
author = "hrhr49"
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodefences = true
copyright = "Copyright © hrhr49; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "konblue"

# [outputs]
#   home = ["HTML", "JSON"]

[menu]
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 10
  # [[menu.main]]
  #   identifier = "archives"
  #   name = "Archives"
  #   url = "/archives/"
  #   weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.goldmark.extensions]
    definitionList = false
    footnote = false
    linkify = true
    strikethrough = true
    table = true
    taskList = false
    typographer = false
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
